# workflow 이름
name: test-CI

# workflow가 언제 실행될지에 대한 설명(When)
on:
  # main 브랜치에 pr을 올리는 경우(main 브랜치에서 분기한 브랜치도 실행된다.)
  pull_request:
    branches: 
      - 'main'

# workflow가 어떻게 실행될지에 대한 설명(How)
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    # ruby 설치
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    # fastlane 설치
    - name: Install Fastlane
      run: brew install fastlane

    - name: Run a one-line script
      run: echo Hello, world!!!!!!!!!!!!!!!!!